name: Django Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API }}" \
            -H "Content-Type: application/json" \
              "${{ secrets.RENDER_DEPLOY }}"